services:
  - type: web
    name: combobox-api
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install && npm run build
    startCommand: node server.js
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
